/*
 * generated by Xtext
 */
package org.uqbar.project.wollok.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.common.types.TypesFactory;
import org.eclipse.xtext.common.types.access.IJvmTypeProvider;
import org.eclipse.xtext.resource.EObjectAtOffsetHelper;
import org.eclipse.xtext.resource.containers.IAllContainersState;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback;
import org.eclipse.xtext.ui.editor.XtextSourceViewerConfiguration;
import org.eclipse.xtext.ui.editor.actions.IActionContributor;
import org.eclipse.xtext.ui.editor.contentassist.ITemplateProposalProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.model.DocumentTokenSource;
import org.eclipse.xtext.ui.editor.model.TerminalsTokenTypeToPartitionMapper;
import org.eclipse.xtext.ui.editor.model.XtextDocumentProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.util.PluginProjectFactory;
import org.eclipse.xtext.ui.wizard.IProjectCreator;
import org.eclipse.xtext.xbase.jvmmodel.IJvmModelAssociations;
import org.uqbar.project.wollok.interpreter.WollokClassFinder;
import org.uqbar.project.wollok.manifest.BasicWollokManifestFinder;
import org.uqbar.project.wollok.manifest.WollokManifestFinder;
import org.uqbar.project.wollok.ui.autoedit.TokenTypeToPartitionMapper;
import org.uqbar.project.wollok.ui.editor.WollokSourceViewerConfiguration;
import org.uqbar.project.wollok.ui.editor.annotations.WOverrideIndicatorModelListener;
import org.uqbar.project.wollok.ui.editor.annotations.WOverrideRulerAction;
import org.uqbar.project.wollok.ui.editor.hyperlinking.WollokEObjectAtOffsetHelper;
import org.uqbar.project.wollok.ui.editor.model.WollokDocumentProvider;
import org.uqbar.project.wollok.ui.editor.model.WollokDocumentTokenSource;
import org.uqbar.project.wollok.ui.editor.templates.WollokTemplateProposalProvider;
import org.uqbar.project.wollok.ui.highlight.WollokHighlightingCalculator;
import org.uqbar.project.wollok.ui.highlight.WollokHighlightingConfiguration;
import org.uqbar.project.wollok.ui.hover.WollokEObjectHoverProvider;
import org.uqbar.project.wollok.ui.wizard.WollokProjectCreator;
import org.uqbar.project.wollok.ui.wizard.WollokProjectFactory;
import org.uqbar.project.wollok.utils.DummyJvmModelAssociations;
import org.uqbar.project.wollok.utils.DummyJvmTypeProviderFactory;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.name.Names;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WollokDslUiModule extends org.uqbar.project.wollok.ui.AbstractWollokDslUiModule {
	
	public WollokDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public void configure(Binder binder) {
		super.configure(binder);

		binder.bind(EObjectAtOffsetHelper.class).to(WollokEObjectAtOffsetHelper.class);
		binder.bind(IEObjectHoverProvider.class).to(WollokEObjectHoverProvider.class);
	}
		
	@Override
	public Class<? extends ITemplateProposalProvider> bindITemplateProposalProvider() {
		return WollokTemplateProposalProvider.class;
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
		 return WollokHighlightingConfiguration.class;
	}
	
	public void configureOverrideIndicatorSupport(Binder binder) {
		binder.bind(IXtextEditorCallback.class).annotatedWith(Names.named("OverrideIndicatorModelListener")).to(WOverrideIndicatorModelListener.class);
		binder.bind(IActionContributor.class).annotatedWith(Names.named("OverrideIndicatorRulerAction")).to(WOverrideRulerAction.class);
		
		binder.bind(IHighlightingConfiguration.class).to(WollokHighlightingConfiguration.class);
		binder.bind(ISemanticHighlightingCalculator.class).to(WollokHighlightingCalculator.class);
		
		// Hacks to be able to reuse the logic to extract method from refactoring
		binder.bind(IJvmModelAssociations.class).to(DummyJvmModelAssociations.class); 
		binder.bind(IJvmTypeProvider.Factory.class).to(DummyJvmTypeProviderFactory.class);
		binder.bind(TypesFactory.class).toInstance(org.eclipse.xtext.common.types.TypesFactory.eINSTANCE);
	}
	
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return WollokProjectCreator.class;
	}
	
	@Override
	public Provider<IAllContainersState> provideIAllContainersState() {
		  return org.eclipse.xtext.ui.shared.Access.getWorkspaceProjectsState();
	}

	public Class<? extends WollokManifestFinder> bindWollokManifestFinder(){
		return BasicWollokManifestFinder.class;
	}
	
	public Class<? extends PluginProjectFactory> bindPluginProjectFactory(){
		return WollokProjectFactory.class;
	}

	public Class<? extends XtextDocumentProvider> bindXtextDocumentProvider(){
		return WollokDocumentProvider.class;
	}
	
	public Class<? extends XtextSourceViewerConfiguration> bindSourceViewerConfiguration(){
		return WollokSourceViewerConfiguration.class;
	}
	
	public Class<? extends DocumentTokenSource> bindDocumentTokenSource(){
		return WollokDocumentTokenSource.class;
	}
	
	public Class<? extends TerminalsTokenTypeToPartitionMapper> bindTerminalsTokenTypeToPartitionMapper() {
		return TokenTypeToPartitionMapper.class;
	}
	
}
