/*
 * generated by Xtext
 */
package org.uqbar.project.wollok.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
//@FinalFieldsConstructor
//class WollokDslUiModule extends AbstractWollokDslUiModule {
//}
