/*
 * generated by Xtext
 */
package org.uqbar.project.wollok.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.resource.EObjectAtOffsetHelper;
import org.eclipse.xtext.resource.containers.IAllContainersState;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback;
import org.eclipse.xtext.ui.editor.actions.IActionContributor;
import org.eclipse.xtext.ui.editor.contentassist.ITemplateProposalProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.wizard.IProjectCreator;
import org.uqbar.project.wollok.manifest.WollokManifestFinder;
import org.uqbar.project.wollok.ui.editor.annotations.WOverrideIndicatorModelListener;
import org.uqbar.project.wollok.ui.editor.annotations.WOverrideRulerAction;
import org.uqbar.project.wollok.ui.editor.hyperlinking.WollokEObjectAtOffsetHelper;
import org.uqbar.project.wollok.ui.editor.templates.WollokTemplateProposalProvieder;
import org.uqbar.project.wollok.ui.highlight.WollokHighlightingCalculator;
import org.uqbar.project.wollok.ui.highlight.WollokHighlightingConfiguration;
import org.uqbar.project.wollok.ui.manifest.WollokJDTManifestFinder;
import org.uqbar.project.wollok.ui.wizard.WollokProjectCreator;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.name.Names;

/**
 * Use this class to register components to be used within the IDE.
 */
public class WollokDslUiModule extends org.uqbar.project.wollok.ui.AbstractWollokDslUiModule {
	
	public WollokDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		binder.bind(EObjectAtOffsetHelper.class).to(WollokEObjectAtOffsetHelper.class);
	}
	
	@Override
	public Class<? extends ITemplateProposalProvider> bindITemplateProposalProvider() {
		return WollokTemplateProposalProvieder.class;
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
		 return WollokHighlightingConfiguration.class;
	}
	
	public void configureOverrideIndicatorSupport(Binder binder) {
		binder.bind(IXtextEditorCallback.class).annotatedWith(Names.named("OverrideIndicatorModelListener")).to(WOverrideIndicatorModelListener.class);
		binder.bind(IActionContributor.class).annotatedWith(Names.named("OverrideIndicatorRulerAction")).to(WOverrideRulerAction.class);
		
		binder.bind(IHighlightingConfiguration.class).to(WollokHighlightingConfiguration.class);
		binder.bind(ISemanticHighlightingCalculator.class).to(WollokHighlightingCalculator.class);
	}
	
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return WollokProjectCreator.class;
	}
	
	@Override
	public Provider<IAllContainersState> provideIAllContainersState() {
		  return org.eclipse.xtext.ui.shared.Access.getWorkspaceProjectsState();
	}

	public Class<? extends WollokManifestFinder> bindWollokManifestFinder(){
		return WollokJDTManifestFinder.class;
	}
}
