package org.uqbar.project.wollok.tests.quickfix

import org.junit.Test
import org.uqbar.project.wollok.ui.Messages

class MethodOnWKODoesntExistQuickFixTest extends AbstractWollokQuickFixTestCase {

	@Test
	def void createNonExistingMethodOnSameFile() {
		val initial = #['''
			object anObject{
				
			}
			
			object anotherObject{
				method aMethod(){
					anObject.otherMethod()
				}
			}
		''']

		val result = #['''
			object anObject{
				method otherMethod() {
					//TODO: Autogenerated Code ! 
				}
				
			}
			
			object anotherObject{
				method aMethod(){
					anObject.otherMethod()
				}
			}
		''']
		assertQuickfix(initial, result, Messages.WollokDslQuickfixProvider_createMethod_name)
	}

	@Test
	def void createNonExistingMethodOnDifferentFile() {
		val initial = #['''
			object anObject{
				
			}
		''',
		'''
			import file0.anObject

			object anotherObject{
				method aMethod(){
					anObject.otherMethod()
				}
			}
		''']

		val result = #['''
			object anObject{
				method otherMethod() {
					//TODO: Autogenerated Code ! 
				}
				
			}
		''',
		'''
			import file0.anObject
			
			object anotherObject{
				method aMethod(){
					anObject.otherMethod()
				}
			}
		''']
		assertQuickfix(initial, result, Messages.WollokDslQuickfixProvider_createMethod_name)
	}

}
	