/*
 * generated by Xtext
 */
package org.uqbar.project.wollok.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.uqbar.project.wollok.wollokDsl.WFile

@RunWith(XtextRunner)
@InjectWith(WollokDslInjectorProvider)
class WollokDslParsingTest {
	@Inject
	ParseHelper<WFile> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
