/*
 * generated by Xtext
 */
package org.uqbar.project.wollok


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
//class WollokDslRuntimeModule extends AbstractWollokDslRuntimeModule {
//}
