/*
* generated by Xtext
*/
package org.uqbar.project.wollok;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class WollokDslStandaloneSetup extends WollokDslStandaloneSetupGenerated{

	public static void doSetup() {
		new WollokDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

