/*
 * generated by Xtext
 */
package org.uqbar.project.wollok;

import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.impl.ImportUriGlobalScopeProvider;
import org.eclipse.xtext.scoping.impl.ImportUriResolver;
import org.uqbar.project.wollok.scoping.WollokImportURIResolver;
import org.uqbar.project.wollok.scoping.WollokResourceDescriptionStrategy;
import org.uqbar.project.wollok.semantics.XSemanticsTypeSystem;
import org.uqbar.project.wollok.typesystem.TypeSystem;

import com.google.inject.Binder;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WollokDslRuntimeModule extends org.uqbar.project.wollok.AbstractWollokDslRuntimeModule {

	@Override
	public void configure(Binder binder) {
		super.configure(binder);
		// TYPE SYSTEM
		binder.bind(TypeSystem.class).to(XSemanticsTypeSystem.class);
	}
	
	// customize exported objects
	public Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
		return WollokResourceDescriptionStrategy.class;
	}
	
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider(){
		return ImportUriGlobalScopeProvider.class;
	}
	
	public Class<? extends ImportUriResolver> bindImportUriResolver(){
		return WollokImportURIResolver.class;
	}

	
}
