/*
 * generated by Xtext
 */
package org.uqbar.project.wollok


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
//class WollokDslStandaloneSetup extends WollokDslStandaloneSetupGenerated {
//
//	def static void doSetup() {
//		new WollokDslStandaloneSetup().createInjectorAndDoEMFRegistration()
//	}
//}
