/*
* generated by Xtext
*/
package org.uqbar.project.wollok;

import com.google.inject.Binder;
import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;


/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class WollokDslStandaloneSetup extends WollokDslStandaloneSetupGenerated implements Module{
	public Injector createInjector() {
		return Guice.createInjector(new org.uqbar.project.wollok.WollokDslRuntimeModule(),this);
	}
	
	@Override
	public void configure(Binder binder) {
	}
}

